import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import Header from "../components/Header";
import Loader from "../components/Loader";
import Footer from "../layouts/Footer";

const About = () => {
  const [load, setLoad] = useState(true);
  useEffect(() => {
    setLoad(false);
  }, []);
  const jobs = [
    {
      workshop: "7Seasol",
      designation: "Front-End Developer",
      text: `August 2021 to February 2022 (7 Months) </br>
      I have worked as React and Front-end developer at 7Seasol, Surat (Gujarat).`,
    },
    {
      workshop: "Explarity Solution Pvt Ltd",
      designation: "Front End Developer",
      text: `March 2022 to continue (Present) </br>
      I am working as React and Front-end developer at Explarity Solution Pvt Ltd, Sangli (Maharshtra).`,
    },
    // {
    //   workshop: "Webworks",
    //   designation: "Graphic Designer",
    //   text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates perferendis totam enim. Nesciunt porro dolores expedita dolor necessitatibus deserunt nemo.",
    // },
  ];
  const myLoader = ({ src }) => {
    return `${src}`;
  };
  return (
    <>
      <Head>
        <title>Portfolio | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!load ? (
        <div className="overFlow-scroll">
          <div className="page">
            <div className="container">
              <Header
                text="About"
                colorText="Me"
                desc="Let me tell you a few things..."
              />
              <div className="details">
                <div className="row">
                  <div className="col-lg-4 col-md-4 col-sm-12 d-flex justify-content-center align-items-start">
                    <div className="profile">
                      <Image
                        src={"/assets/img/profile.jpg"}
                        loader={myLoader}
                        width={"250px"}
                        height={"250px"}
                        objectFit={"cover"}
                        className="profile-img"
                        alt="profile"
                      />
                    </div>
                  </div>
                  <div className="col-lg-8 col-md-8 col-sm-12">
                    <div className="detail-text">
                      <h5>BIO</h5>
                      {/* <p>
                       My self <span>Arshad Qadri </span> I am from Sangli,
                       Maharashtra. I am BCA graduated and passout in 2020.
                       Currently I am working in
                       <span> Explarity Solution Pvt. Ltd. </span>I have{" "}
                       <span>One Year</span> of experience. <br />I have skills
                       <b>
                         {" "}
                         HTML, CSS, Bootstrap, Tailwindcss, Javascript, Reactjs,
                         Nextjs, Redux, Nodejs
                       </b>{" "}
                       etc.
                     </p> */}
                      <p>
                        Hello, I'm Arshad Qadri, a dedicated React developer
                        with a BCA degree from Shivaji University, Kolhapur,
                        graduated in 2020. Currently, I bring over 2+ years of
                        valuable experience to the dynamic team at Explarity
                        Solution Pvt Ltd.
                      </p>

                      <p>
                        My skill set encompasses a wide array of technologies
                        crucial for modern web development. Proficient in HTML,
                        CSS, Bootstrap, Tailwind CSS, and Chakra UI, I
                        specialize in creating visually appealing and responsive
                        user interfaces. Leveraging tools like Reactstrap, I
                        ensure the seamless integration of design components.
                      </p>

                      <p>
                        At the core of my development expertise is a strong
                        command of JavaScript and TypeScript, enabling me to
                        build interactive and dynamic web applications. My
                        proficiency extends to popular front-end frameworks such
                        as React.js and Next.js, showcasing my commitment to
                        staying current in the ever-evolving landscape of web
                        development.
                      </p>

                      <p>
                        In the realm of state management, I leverage the power
                        of Redux to enhance the performance and maintainability
                        of complex applications. My versatility extends to the
                        back end, where I am skilled in Node.js and Express, and
                        have hands-on experience with databases including
                        MongoDB and MySQL.
                      </p>

                      <p>
                        Beyond crafting robust and efficient applications, I am
                        well-versed in SEO implementation, ensuring that the
                        solutions I develop are not only functional but also
                        optimized for search engines. This holistic approach
                        underscores my commitment to delivering high-quality,
                        user-friendly, and discoverable web solutions.
                      </p>

                      <p>
                        I thrive in collaborative environments that encourage
                        innovation, where my passion for pushing the boundaries
                        of web development can flourish. My journey as a React
                        developer has equipped me with a diverse skill set and a
                        proven track record of delivering successful projects. I
                        am excited about the opportunity to contribute my skills
                        and enthusiasm to future endeavors in the field of web
                        development.
                      </p>

                      <p>
                        Thank you for considering my profile. I look forward to
                        the prospect of collaborating on exciting projects.
                      </p>
                    </div>
                  </div>
                  <div className="row gy-4 mx-0 mb-5">
                    {jobs.map((item, ind) => (
                      <div className="col-lg-6 col-sm-12" key={ind}>
                        <div className="job-info">
                          <h3>{item.workshop}</h3>
                          <h5> {item.designation} </h5>
                          <p
                            dangerouslySetInnerHTML={{ __html: `${item.text}` }}
                          ></p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <Footer />
        </div>
      ) : (
        <Loader />
      )}
    </>
  );
};

export default About;
