import Head from "next/head";
import Image from "next/image";
import React from "react";
import Header from "../components/Header";
import Footer from "../layouts/Footer";

const About = () => {
  const jobs = [
    {
      workshop: "123 Webshop",
      designation: "Full Stack Developer",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates perferendis totam enim. Nesciunt porro dolores expedita dolor necessitatibus deserunt nemo.",
    },
    {
      workshop: "Designers ABC",
      designation: "Front End Developer",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates perferendis totam enim. Nesciunt porro dolores expedita dolor necessitatibus deserunt nemo.",
    },
    {
      workshop: "Webworks",
      designation: "Graphic Designer",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates perferendis totam enim. Nesciunt porro dolores expedita dolor necessitatibus deserunt nemo.",
    },
  ];
  const myLoader = ({ src }) => {
    return `${src}`;
  };
  return (
    <>
      <Head>
        <title>Portfolio | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overFlow-scroll">
        <div className="page">
          <div className="container">
            <Header
              text="About"
              colorText="Me"
              desc="Let me tell you a few things..."
            />
            <div className="details">
              <div className="row">
                <div className="col-lg-4 col-md-4 col-sm-12 d-flex justify-content-center align-items-center">
                  <div className="profile">
                    <Image
                      src={"/assets/img/profile.jpg"}
                      loader={myLoader}
                      width={"250px"}
                      height={"250px"}
                      objectFit={"cover"}
                      className="profile-img"
                      alt="profile"
                    />
                  </div>
                </div>
                <div className="col-lg-8 col-md-8 col-sm-12">
                  <div className="detail-text">
                    <h5>BIO</h5>
                    <p>
                      My self <span>Arshad Qadri </span> I am from Sangli,
                      Maharashtra. I am BCA graduated and passout in 2020.
                      Currently I am working in
                      <span> Explarity Solution Pvt. Ltd. </span>I have total
                      experience <span>Six Months </span>+. <br />I have skills
                      <b>
                        {" "}
                        HTML, CSS, Bootstrap, Tailwindcss, Javascript, Reactjs,
                        Nextjs, Redux, Nodejs
                      </b>{" "}
                      etc.
                    </p>
                  </div>
                </div>
                <div className="row gy-4 mx-0 mb-5">
                  {jobs.map((item, ind) => (
                    <div className="col-lg-4 col-sm-12" key={ind}>
                      <div className="job-info">
                        <h3>{item.workshop}</h3>
                        <h5> {item.designation} </h5>
                        <p>{item.text}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default About;
