import Head from "next/head";
import React from "react";
import Header from "../components/Header";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Portfolio | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <div className="container">
          <Header
            text="Contact"
            colorText="Me"
            desc="This is how you can reach me..."
          />
        </div>
      </div>
    </>
  );
};

export default Contact;
