import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Loader from "../components/Loader";
import ReactTypedComponent from "../components/ReactTyped";
import { FaLinkedin, FaGithubSquare } from "react-icons/fa";
import Link from "next/link";

export default function Home() {
  const [load, setLoad] = useState(true);
  const myLoader = ({ src }) => {
    return `${src}`;
  };
  useEffect(() => {
    setLoad(false);
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!load ? (
        <div className="home">
          <Image
            src={"/assets/img/bg.jpg"}
            loader={myLoader}
            layout={"fill"}
            objectFit={"cover"}
            alt={"bacground"}
          />
          <div className="leftside">
            <div className="left-container">
              <div>
                <div className="devider">
                  <Link href="https://www.linkedin.com/in/arshad-qadri/">
                    <a target="_blank" className="linkedin-icon" rel="referrer">
                      <FaLinkedin size={30} color="#fff" />
                    </a>
                  </Link>
                  <Link href="https://github.com/arshad-qadri">
                    <a target="_blank" className="github-icon" rel="referrer">
                      <FaGithubSquare size={30} color="#fff" />
                    </a>
                  </Link>
                </div>
              </div>
              <div className="">
                <h1>
                  Arshad <span className="lastname">Qadri</span>
                </h1>
                <div className="text">
                  <ReactTypedComponent />
                </div>
                <div className="btn-grp">
                  <a
                    href="/assets/resume/Arshad-React-Resume.pdf"
                    className="download-button"
                    download
                  >
                    Download Resume
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <Loader />
      )}
    </>
  );
}
