import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Loader from "../components/Loader";
import { FaPlay } from "react-icons/fa";
import ReactTypedComponent from "../components/ReactTyped";

export default function Home() {
  const [load, setLoad] = useState(true);
  const myLoader = ({ src }) => {
    return `${src}`;
  };
  useEffect(() => {
    setLoad(false);
  }, []);

  return (
    <>
      <Head>
        <title>Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!load ? (
        <div className="home">
          <Image
            src={"/assets/img/bg.jpg"}
            loader={myLoader}
            layout={"fill"}
            objectFit={"cover"}
            alt={"bacground"}
          />
          <div className="leftside">
            <h1>
              Arshad <span className="lastname">Qadri</span>
            </h1>
            <div className="text">
              {/* <p>MERN Stack Developer, Frontend Designer</p> */}
              <ReactTypedComponent />
            </div>
            <div className="btn-grp">
              <a
                href="/assets/resume/Arshad-React-Resume.pdf"
                className="download-button"
                download
              >
                Download Resume
              </a>
              {/* <button title="Introduction myself" className="play-btn">
                <FaPlay color="#fff" size={30} />
              </button> */}
            </div>
          </div>
        </div>
      ) : (
        <Loader />
      )}
    </>
  );
}
