import Head from "next/head";
import Image from "next/image";
import React from "react";
import Header from "../components/Header";
import Footer from "../layouts/Footer";

const Mywork = () => {
  const myWorks = [
    {
      image: "crm.png",
      gitLink: "https://github.com/arshad-qadri/nextjs-crm-frontend",
      live: "https://crm-frontend-01.netlify.app",
    },
    {
      image: "filtertable.png",
      gitLink: "https://github.com/arshad-qadri/filter-table-data",
      live: "https://dhzyl.csb.app",
    },
    {
      image: "Github-User.png",
      gitLink: "https://github.com/arshad-qadri/github-user",
      live: "https://oione.sse.codesandbox.io",
    },
    {
      image: "randomejoke.png",
      gitLink: "https://github.com/arshad-qadri/Random-Jokes",
      live: "https://random-joke-react.herokuapp.com",
    },
    {
      image: "reactportfolio.png",
      gitLink: "https://github.com/arshad-qadri/React-Portfolio",
      live: "https://react-arshad-portfolio.herokuapp.com",
    },
    {
      image: "URL Source.png",
      gitLink: "https://github.com/arshad-qadri/url-project-frontend",
      live: "https://my-urlproject.web.app/",
    },
  ];
  const myLoader = ({ src }) => {
    return `${src}`;
  };
  //api.urlbox.io/v1/T6LcLYJSQb9WkOPJ/png?url=${websiteUrl}
  https: return (
    <>
      <Head>
        <title>Portfolio | My work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overFlow-scroll">
        <div className="page">
          <div className="container">
            <Header
              text="My"
              colorText="Work"
              desc="Check out some of my projects..."
            />
            <div className="row gy-3">
              {myWorks.map((item, ind) => (
                <div className="col-lg-4 col-md-6 col-sm-12 my-3" key={ind}>
                  <div className="projet">
                    <figure
                      style={{
                        width: "100%",
                        height: "200px",
                        position: "relative",
                      }}
                    >
                      <Image
                        src={`/assets/img/${item.image}`}
                        layout={"fill"}
                        loader={myLoader}
                        objectFit={"cover"}
                        alt={"projects image"}
                      />
                      {/* <Image
                        src={`https://api.apiflash.com/v1/urltoimage?access_key=212e6657f9d84dffb90369c555e1eda2&wait_until=page_loaded&url=${item.live}&width=410`}
                        layout={"fill"}
                        loader={myLoader}
                        objectFit={"cover"}
                        alt={"projects image"}
                      /> */}
                    </figure>
                    <a
                      className="live-preview"
                      href={item.live}
                      target={"_blank"}
                      rel="noreferrer"
                    >
                      Live preview
                    </a>

                    <a
                      className="source-code"
                      href={item.gitLink}
                      target={"_blank"}
                      rel="noreferrer"
                    >
                      Source code
                    </a>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default Mywork;
