import Head from "next/head";
import React from "react";
import Header from "../components/Header";

const Mywork = () => {
  return (
    <>
      <Head>
        <title>Portfolio | My work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <div className="container">
          <Header
            text="My"
            colorText="Work"
            desc="Check out some of my projects..."
          />
        </div>
      </div>
    </>
  );
};

export default Mywork;
